title: sra-vjti
url: sra-vjti.github.io
author: sra-vjti
email: sraworkshop@gmail.com
description: > 
  The Society of Robotics and Automation is a society for VJTI students. As the name suggests, we deal with Robotics, Machine Vision and Automation
show_excerpts: false # set to true to show excerpts on the homepage

paginate: 5
paginate_path: "/blog/page:num/"

tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tag

# jekyll-dash date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
dash:
  date_format: "%d %b %Y"

  # generate social links in footer
  # supported colors: green, red, orange, blue, cyan, pink, teal, yellow, indigo, purple
  social_links:
    - url: https://www.instagram.com/sra_vjti/
      icon: instagram
      color: pink
    - url: https://www.linkedin.com/company/society-of-robotics-and-automation-vjti/
      icon: linkedin
      color: blue
    - url: https://www.facebook.com/pg/sra.vjti/posts/
      icon: facebook
      color: cyan
    - url: https://www.youtube.com/channel/UC-g67CbV2Iu30n7TvipRiCA/featured
      icon: youtube
      color: red
    - url: https://github.com/sra-vjti
      icon: github-square
      color: yellow

# Build settings
remote_theme: bitbrain/jekyll-dash

plugins:
  - liquid-md5
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll/tagging
  
avatar_source: github
github_username: sra-vjti